# Generated by Django 4.1.6 on 2023-02-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=250)),
                ('subject', models.CharField(max_length=250)),
                ('desc', models.TextField()),
            ],
        ),
    ]
